package linqable

import (
	"fmt"
	"os"
	"reflect"

	"github.com/dave/jennifer/jen"
)

// Linqablize : generate a new `.go` file with specified type
//
// Parameters
//
// t reflect.Type               => the specified type
//
// packageName string           => package name of the `.go` file
//
// opts ...LinqablizeOptionFunc => optional parameters
//
// Optional Parameters
//
// IsImportedType() => output file will import the package of the specified type
//
// IsNumericType() => output file will contain the methods such as Max(), Min() ...
//
// HasDefaultValue(stringValue string) => Set default value of your type, or using zero value as default.
func Linqablize(t reflect.Type, packageName string, opts ...LinqablizeOptionFunc) {
	var opt linqablizeOption
	for _, optFunc := range opts {
		optFunc(&opt)
	}

	linqableTypeName := "Linqable" + t.Name()
	typeName := t.Name()

	jenFile := jen.NewFile(packageName)
	jenFile.HeaderComment(`Code generated by linqable.go Do NOT EDIT.`)
	// #region imported type
	if opt.isImportedType {
		typeName = t.String()
		jenFile.Id("import").Id("\"" + t.PkgPath() + "\"").
			Line()
	}
	// #endregion imported type
	var defaultValueCode string
	if opt.hasDefaultValue {
		defaultValueCode = "defaultValue := " + opt.defaultValue
	} else {
		defaultValueCode = "var defaultValue " + typeName
	}
	predicateCode := jen.Id("predicate").Func().Call(jen.Id(typeName)).Id("bool")

	jenFile.Line()
	jenFile.Id("type").Id(linqableTypeName).Op("[]").Id(typeName)
	jenFile.Line()

	// #region constructor
	jenFile.Func().Id(fmt.Sprintf("NewLinqable%s", t.Name())).Call(jen.Id("si").Op("[]").Id(typeName)).Id(linqableTypeName).Block(jen.Return(jen.Id("si")))
	// #endregion constructor
	jenFile.Line()

	// #region Where
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Where").Call(predicateCode).Id(linqableTypeName).
		Block(jen.Id("res").Op(":=").Op("[]").Id(typeName).Op("{}").
			Line().For(jen.Id("_").Op(",").Id("elem").Op(":=").Id("range").Id("si").
			Block(jen.If(jen.Id("predicate(elem)")).
				Block(jen.Id("res").Op("=").Id("append(res, elem)"))).
			Line().Return(jen.Id("res"))))
	// #endregion Where
	jenFile.Line()

	// #region Reverse
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Reverse").Call(predicateCode).Id(linqableTypeName).
		Block(jen.For(jen.Id("i, j := 0, len(si)-1; i < j; i, j = i+1, j-1")).Block(jen.Id("si[i], si[j] = si[j], si[i]")).
			Line().Return(jen.Id("si")))
	// #endregion Reverse
	jenFile.Line()

	// #region Contains
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Contains").Call(jen.Id("target").Id(typeName)).Id("bool").
		Block(jen.For(jen.Id("_").Op(",").Id("elem").Op(":=").Id("range").Id("si").
			Block(jen.If(jen.Id("elem == target")).
				Block(jen.Return(jen.Id("true")))).
			Line().Return(jen.Id("false"))))
	// #endregion Contains
	jenFile.Line()

	// #region Count
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Count").Call(predicateCode).Id("int").
		Block(jen.Id("var count int").
			Line().For(jen.Id("_").Op(",").Id("elem").Op(":=").Id("range").Id("si").
			Block(jen.If(jen.Id("predicate(elem)")).
				Block(jen.Id("count++"))).
			Line().Return(jen.Id("count"))))
	// #endregion Count
	jenFile.Line()

	// #region Any
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Any").Call(predicateCode).Id("bool").
		Block(jen.For(jen.Id("_").Op(",").Id("elem").Op(":=").Id("range").Id("si").
			Block(jen.If(jen.Id("predicate(elem)")).
				Block(jen.Return(jen.Id("true")))).
			Line().Return(jen.Id("false"))))
	// #endregion Any
	jenFile.Line()

	// #region All
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("All").Call(predicateCode).Id("bool").
		Block(jen.For(jen.Id("_").Op(",").Id("elem").Op(":=").Id("range").Id("si").
			Block(jen.If(jen.Id("predicate(elem)")).
				Block(jen.Continue()).Else().
				Block(jen.Return(jen.Id("false")))).
			Line().Return(jen.Id("true"))))
	// #endregion All
	jenFile.Line()

	// #region Append
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Append").Call(jen.Id("newItem").Id(typeName)).Id(linqableTypeName).
		Block(jen.Return(jen.Id("append(si, newItem)")))
	// #endregion Append
	jenFile.Line()

	// #region Prepend
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Prepend").Call(jen.Id("newItem").Id(typeName)).Id(linqableTypeName).
		Block(jen.Return(jen.Id("append").Call(jen.Op("[]").Id(typeName).Id("{newItem}").Id(", si.ToSlice()..."))))
	// #endregion Prepend
	jenFile.Line()

	// #region ElementAt
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("ElementAt").Call(jen.Id("index int")).Id(typeName).
		Block(jen.If(jen.Id("index >= len(si)")).
			Block(jen.Id(`panic("linq: ElementAt() out of index")`)).
			Line().Return(jen.Id("si[index]")))
	// #endregion ElementAt
	jenFile.Line()

	// #region ElementAtOrDefault
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("ElementAtOrDefault").Call(jen.Id("index int")).Id(typeName).
		Block(jen.Id(defaultValueCode).
			Line().If(jen.Id("index >= len(si)")).
			Block(jen.Return(jen.Id("defaultValue"))).
			Line().Return(jen.Id("si[index]")))
	// #endregion ElementAtOrDefault
	jenFile.Line()

	// #region Empty
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Empty").Call().Id(linqableTypeName).
		Block(jen.Return(jen.Id("New" + linqableTypeName).Call(jen.Op("[]").Id(typeName).Op("{}"))))
	// #endregion Empty
	jenFile.Line()

	// #region First
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("First").Call(predicateCode).Id(typeName).
		Block(jen.If(jen.Id("len(si) <= 0")).
			Block(jen.Panic(jen.Id(`"linq: First() empty set"`))).
			Line().For(jen.Id("_").Op(",").Id("elem").Op(":=").Id("range").Id("si").
			Block(jen.If(jen.Id("predicate(elem)")).
				Block(jen.Return(jen.Id("elem")))).
			Line().Panic(jen.Id(`"linq: First() no match element in the slice"`))))
	// #endregion First
	jenFile.Line()

	// #region FirstOrDefault
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("FirstOrDefault").Call(predicateCode).Id(typeName).
		Block(jen.Id(defaultValueCode).
			Line().If(jen.Id("len(si) <= 0")).
			Block(jen.Return(jen.Id("defaultValue"))).
			Line().For(jen.Id("_").Op(",").Id("elem").Op(":=").Id("range").Id("si").
			Block(jen.If(jen.Id("predicate(elem)")).
				Block(jen.Return(jen.Id("elem")))).
			Line().Return(jen.Id("defaultValue"))))
	// #endregion FirstOrDefault
	jenFile.Line()

	// #region Last
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Last").Call(predicateCode).Id(typeName).
		Block(jen.If(jen.Id("len(si) <= 0")).
			Block(jen.Panic(jen.Id(`"linq: Last() empty set"`))).
			Line().For(jen.Id("i := len(si) - 1; i >= 0; i--")).
			Block(jen.If(jen.Id("predicate(si[i])")).
				Block(jen.Return(jen.Id("si[i]")))).
			Line().Panic(jen.Id(`"linq: Last() no match element in the slice"`)))
	// #endregion Last
	jenFile.Line()

	// #region LastOrDefault
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("LastOrDefault").Call(predicateCode).Id(typeName).
		Block(jen.Id(defaultValueCode).
			Line().If(jen.Id("len(si) <= 0")).
			Block(jen.Return(jen.Id("defaultValue"))).
			Line().For(jen.Id("i := len(si) - 1; i >= 0; i--")).
			Block(jen.If(jen.Id("predicate(si[i])")).
				Block(jen.Return(jen.Id("si[i]")))).
			Line().Return(jen.Id("defaultValue")))
	// #endregion LastOrDefault
	jenFile.Line()

	// #region Single
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Single").Call(predicateCode).Id(typeName).
		Block(jen.If(jen.Id("len(si) <= 0")).
			Block(jen.Panic(jen.Id(`"linq: Single() empty set"`))).
			Line().If(jen.Id("si.Count(predicate) == 1")).
			Block(jen.Return(jen.Id("si.First(predicate)"))).
			Line().Panic(jen.Id(`"linq: Single() eligible data count is not unique"`)))
	// #endregion Single
	jenFile.Line()

	// #region SingleOrDefault
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("SingleOrDefault").Call(predicateCode).Id(typeName).
		Block(jen.Id(defaultValueCode).
			Line().If(jen.Id("len(si) <= 0")).
			Block(jen.Return(jen.Id("defaultValue"))).
			Line().If(jen.Id("si.Count(predicate) == 1")).
			Block(jen.Return(jen.Id("si.First(predicate)"))).
			Line().Return(jen.Id("defaultValue")))
	// #endregion SingleOrDefault
	jenFile.Line()

	// #region Take
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Take").Call(jen.Id("n int")).Id(linqableTypeName).
		Block(jen.If(jen.Id("n < 0 || n >= len(si)")).
			Block(jen.Panic(jen.Id(`"Linq: Take() out of index"`))).
			Line().Id("res").Op(":=").Op("[]").Id(typeName).Op("{}").
			Line().For(jen.Id("i := 0; i < n; i++")).
			Block(jen.Id("res = append(res, si[i])")).
			Line().Return(jen.Id("res")))
	// #endregion Take
	jenFile.Line()

	// #region TakeWhile
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("TakeWhile").Call(predicateCode).Id(linqableTypeName).
		Block(jen.Id("res").Op(":=").Op("[]").Id(typeName).Op("{}").
			Line().For(jen.Id("i := 0; i < len(si); i++")).
			Block(jen.If(jen.Id("predicate(si[i])").
				Block(jen.Id("res = append(res, si[i])")).Else().
				Block(jen.Return(jen.Id("res"))))).
			Line().Return(jen.Id("res")))
	// #endregion TakeWhile
	jenFile.Line()

	// #region TakeLast
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("TakeLast").Call(jen.Id("n int")).Id(linqableTypeName).
		Block(jen.If(jen.Id("n < 0 || n >= len(si)")).
			Block(jen.Panic(jen.Id(`"Linq: TakeLast() out of index"`))).
			Line().Return(jen.Id("si.Skip(len(si) - n)")))
	// #endregion TakeLast
	jenFile.Line()

	// #region Skip
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Skip").Call(jen.Id("n int")).Id(linqableTypeName).
		Block(jen.If(jen.Id("n < 0 || n >= len(si)")).
			Block(jen.Panic(jen.Id(`"Linq: Skip() out of index"`))).
			Line().Return(jen.Id("si[n:]")))
	// #endregion Skip
	jenFile.Line()

	// #region SkipWhile
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("SkipWhile").Call(predicateCode).Id(linqableTypeName).
		Block(jen.For(jen.Id("i := 0; i < len(si); i++")).
			Block(jen.If(jen.Id("predicate(si[i])").
				Block(jen.Op("continue")).Else().
				Block(jen.Return(jen.Id("si[i:]"))))).
			Line().Return(jen.Id(fmt.Sprintf("%s{}", linqableTypeName))))
	// #endregion SkipWhile
	jenFile.Line()

	// #region SkipLast
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("SkipLast").Call(jen.Id("n int")).Id(linqableTypeName).
		Block(jen.If(jen.Id("n < 0 || n > len(si)")).
			Block(jen.Panic(jen.Id(`"Linq: SkipLast() out of index"`))).
			Line().Return(jen.Id("si.Take(len(si) - n)")))
	// #endregion SkipLast
	jenFile.Line()

	// #region SumInt32
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("SumInt32").Call(jen.Id(fmt.Sprintf("selector func(%s) int32", typeName))).Id("int32").
		Block(jen.Id("var sum int32").
			Line().For(jen.Id("_, elem := range si")).Block(jen.Id("sum += selector(elem)")).
			Line().Return(jen.Id("sum")))
	// #endregion SumInt
	jenFile.Line()

	// #region SumInt16
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("SumInt16").Call(jen.Id(fmt.Sprintf("selector func(%s) int16", typeName))).Id("int16").
		Block(jen.Id("var sum int16").
			Line().For(jen.Id("_, elem := range si")).Block(jen.Id("sum += selector(elem)")).
			Line().Return(jen.Id("sum")))
	// #endregion SumInt16
	jenFile.Line()

	// #region SumInt64
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("SumInt64").Call(jen.Id(fmt.Sprintf("selector func(%s) int64", typeName))).Id("int64").
		Block(jen.Id("var sum int64").
			Line().For(jen.Id("_, elem := range si")).Block(jen.Id("sum += selector(elem)")).
			Line().Return(jen.Id("sum")))
	// #endregion SumInt64
	jenFile.Line()

	// #region SumFloat32
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("SumFloat32").Call(jen.Id(fmt.Sprintf("selector func(%s) float32", typeName))).Id("float32").
		Block(jen.Id("var sum float32").
			Line().For(jen.Id("_, elem := range si")).Block(jen.Id("sum += selector(elem)")).
			Line().Return(jen.Id("sum")))
	// #endregion SumFloat32
	jenFile.Line()

	// #region SumFloat64
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("SumFloat64").Call(jen.Id(fmt.Sprintf("selector func(%s) float64", typeName))).Id("float64").
		Block(jen.Id("var sum float64").
			Line().For(jen.Id("_, elem := range si")).Block(jen.Id("sum += selector(elem)")).
			Line().Return(jen.Id("sum")))
	// #endregion SumFloat64
	jenFile.Line()

	// #region ToSlice
	jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("ToSlice").Call().Op("[]").Id(typeName).Block(jen.Return(jen.Id("si")))
	// #endregion ToSlice

	if opt.isNumericType {
		// #region Max
		jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Max").Call().Id(typeName).
			Block(jen.Id("var max").Id(typeName).
				Line().For(jen.Id("i, elem := range si")).
				Block(jen.If(jen.Id("i == 0 || elem > max")).
					Block(jen.Id("max = elem"))).
				Line().Return(jen.Id("max")))
		// #endregion Max
		jenFile.Line()

		// #region Min
		jenFile.Func().Call(jen.Id("si").Id(linqableTypeName)).Id("Min").Call().Id(typeName).
			Block(jen.Id("var min").Id(typeName).
				Line().For(jen.Id("i, elem := range si")).
				Block(jen.If(jen.Id("i == 0 || elem < min")).
					Block(jen.Id("min = elem"))).
				Line().Return(jen.Id("min")))
		// #endregion Min
		jenFile.Line()
	}

	file, err := os.Create(fmt.Sprintf("linqable_%s.go", t.Name()))
	if err != nil {
		fmt.Println(err)
	}
	defer file.Close()
	file.WriteString(fmt.Sprintf("%#v", jenFile))
}

// LinqablizeOptionFunc : optional parameters of Linqablize()
type LinqablizeOptionFunc func(*linqablizeOption)
type linqablizeOption struct {
	isImportedType  bool
	isNumericType   bool
	hasDefaultValue bool
	defaultValue    string
}

// IsImportedType : optional parameter for the Linqablize()
//
// output file will import the package of the specified type
func IsImportedType() LinqablizeOptionFunc {
	return func(lo *linqablizeOption) {
		lo.isImportedType = true
	}
}

// IsNumericType : optional parameter for the Linqablize()
//
// output file will contain the methods such as Max(), Min() ...
func IsNumericType() LinqablizeOptionFunc {
	return func(lo *linqablizeOption) {
		lo.isNumericType = true
	}
}

// HasDefaultValue : Set the default value of your type, or the default value will be the zero value
//
// Default value should be passed as string. for example : HasDefaultValue(`MyStruct{myInt: 0,myString: "hello world"}`).
// Notice that sometimes you should pass a value with type conversion like HasDefaultValue("int64(8888)")
func HasDefaultValue(stringValue string) LinqablizeOptionFunc {
	return func(lo *linqablizeOption) {
		lo.hasDefaultValue = true
		lo.defaultValue = stringValue
	}
}
